---
title: "git_00"
author: "Iven Santos"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
The sun was shining on the sea,
Shining with all his might:
He did his very best to make
The billows smooth and bright —
And this was odd, because it was

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night.

The moon was shining sulkily,
      Because she thought the sun
Had got no business to be there
      After the day was done —
"It's very rude of him," she said,
      "To come and spoil the fun."
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If anybody made a movie out of my life
I wouldn't like it, but I'd watch it twice
If they halfway tried to do it right
There'd be forty screen writers workin' day and nite.
 
They'd need a research team from Uncle Sam
And go from David Allen Coe to Billy Graham
It would run ten days in the final cut
And that would mean leaving out the gossip smut.
 
And I do request for my children's sake
Don't ever let 'em do a new re-make
The thing I'm sayin' is, don't you see,
Don't make a movie 'bout me
Even for T.V.
Don't make a movie 'bout me. 